#!/usr/bin/env bash

set -ex

for f in "$@"
do
    # Invoke lilypond to compile the file, generating SVG (and MIDI, if the
    # input file specifies MIDI).
    lilypond -dbackend=svg "$f"

    # The name of the compilation output SVG file.
    svg_name="${f%.ly}.svg"

    # Remove unwanted `href` and `xlink:href` attributes generated by lilypond
    # that it uses to link parts of the score to places in the input *.ly file.
    sed -i -E "s/(xlink:)?href=\"[^\"]*\"//g" "$svg_name"

    # Invoke Inkscape to "crop" the score to only the visible parts.
    inkscape --verb=FitCanvasToDrawing \
             --verb=FileSave           \
             --verb=FileQuit           \
             "$svg_name"

    # Get rid of any unwanted Inkscape/Sodipodi-specific attributes.
    inkscape --export-area-drawing --export-plain-svg="$svg_name" "$svg_name"
done
