# The base URL of the site. This is the only required configuration variable.
base_url = "https://eartifacts.github.io/"

# The site title and description. This is used in feeds, by default.
title = "eartifacts"
description = "a small, informal museum of musical artifacts"

# The default language. This is used in feeds.
default_language = "en"

# When set to `true`, the Sass files in the `sass/` directory in the site root
# are compiled.
#
# Sass files in theme directories are always compiled.
compile_sass = false

# The taxonomies to be rendered for the site, and their configuration of the
# default languages.
#
# Example:
#
#     taxonomies = [
#         { name = "tags", feed = true }, # Each tag will have its own feed.
#         { name = "tags" }, # You can have taxonomies with the same name in
#                            # multiple languages.
#         { name = "categories", paginate_by = 5 }, # Five items per page for a
#                                                   # term.
#         { name = "authors" }, # Basic definition: no feed nor pagination.
#     ]
taxonomies = [
    { name = "genres" },
    { name = "minor_genres" },
    { name = "instruments" },
    { name = "years" },
    { name = "artists" },
    { name = "labels" },
]

# When set to `true`, a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

# Configuration of the Markdown rendering.
[markdown]
# When set to `true`, all code blocks are highlighted.
highlight_code = true

# The theme to use for code highlighting.
highlight_theme = "monokai"

# When set to `true`, emoji aliases are translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files, e.g. `:smile:` →
# `😄`.
render_emoji = false

# Whether or not external links are to be opened in a new tab.
#
# If this is `true`, `rel="noopener"` will always automatically be added, for
# security reasons.
external_links_target_blank = true

# Whether or not to set `rel="nofollow"` for all external links.
external_links_no_follow = false

# Whether or not to set `rel="noreferrer"` for all external links.
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots into
# their corresponding typographic forms).
#
# For example: `...` → `…`, `"quote"` → `“quote”`, etc.
smart_punctuation = false
